### ISSUE TITLE
PDFTK Bin Wrapper

### ISSUE THREAD

**Issue by dhollenbeck** [corymickelson/CommonPdf#1]
Thank you for sharing your work. 

Your notes regarding the installation of the PDFTK on AWS Amazon Linux helped me get PDFTK installed on Elastic Beanstalk.  I have not finalized on the best way to get the PDFTK on the EC2 instance and am still exploring the best options. I have recently found this:

https://www.npmjs.com/package/bin-wrapper

Which might easy the pain of installing PDFTK on AWS Amazon Linux.

**Comment by corymickelson** [comment]
Thank you, the comments for use in aws are actually from [here](https://github.com/lob/lambda-pdftk-example). A better explanation can be found [here](https://lob.com/blog/aws-lambda-pdftk/)
