### ISSUE TITLE
Stamp burst needs to be written to tmp/

### ISSUE THREAD

**Issue by corymickelson** [corymickelson/CommonPdf#4]
Stamp class _burst currently is writing burst files to root directory. For execution in AWS this will not allow the file to ever be read. Also burst files are persisting across requests.
 
- Write files to /tmp
- Clean up after newly generated file has successfully been pushed to s3
        Maybe use a .finally() to "rm /tmp/pg*.pdf"

**Comment by tvbarajas** [comment]
Pull request will fix the issue for writing temp files. #5

**Comment by corymickelson** [comment]
Added burst files clean up step.
