### ISSUE TITLE
Help Installing PortableSigner2

### ISSUE THREAD

**Issue by rastko-florencehc** [corymickelson/CommonPdf#7]
Is there anyone who can help with installing PortableSigner2 at Ubuntu Trusty. The docs at PortableSigner2 are totally outdated and not very clear :(

**Comment by corymickelson** [comment]
PortableSigner is just a jar file, you can execute portable signer with java -jar {path to jar} [args]. CommonPdf has been developed with heavy emphasis on AWS Lambda and works "out of the box" for execution in an AWS Lambda environment. Using this in other environments may take additional tweaking and configuration. [Here](https://github.com/pflaeging/PortableSigner2/tree/master/linux) is the docs for installing PortableSigner on linux. Hope that helps.
